### ISSUE TITLE
hiIQ NFT Raffles

### ISSUE THREAD

**Issue by zer0blockchain** [EveripediaNetwork/iq-ethereum#3]
## Solving ##

- multichain hiIQ holders
- passive way for hiIQ holders to participate
- gas efficient way to run NFT raffles

## Proposed Solution ##

- multichain snapshot of hiIQ holders at a predefined block
- all hiIQ holders will be entered into the raffle proportional to their hiIQ holdings at the time of snapshot
- this allows hiIQ holders a way to passively hold and participate
- minimal gas cost for holding a Raffle and scales well
- snapshot stored on IPFS and hash pushed onchain as part of raffle (is this possible to push a ZKP onchain?)
- raffle drawing will use randomness from PRNG or chainlink to resolve the raffle
- winner will receive the NFT

## Onchain info ##

- IPFS hash of all hiIQ holders and their raffle ticket numbers
- IPFS snapshot block number
- Raffle start datetime
- Raffle end datetime
- resolution (could have multiple winners?)
- prize contract (ERC721 contract addr and tokenID)

**Comment by kesar** [comment]
I would suggest to add a onERC721Received interface that will be use to add NFTs to the raffle

https://docs.openzeppelin.com/contracts/4.x/api/token/erc721#IERC721Receiver

you can get as inspiration what aavegotchi does for handle erc1155 and decode the raffleID from data
https://github.com/aavegotchi/aavegotchi-contracts/blob/master/contracts/raffle/RafflesContract.sol#L510

**Comment by kesar** [comment]
done already
